/****************************************************************************
**
** Copyright (C) 2016 pkzju
**
**
** Version	: 0.1.1.0
** Author	: pkzju
** Website	: https://github.com/pkzju
** Project	: https://github.com/pkzju/QSuperConsole
** 
****************************************************************************/

/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MASTER_H
#define MASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * master_scanIndexOD (CO_Data* d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data master_Data;
extern UNS8 motoRealtimeData[16];		/* Mapped at index 0x2000, subindex 0x01 - 0x10 */
extern UNS8 motorSettings[26];		/* Mapped at index 0x2001, subindex 0x01 - 0x1A */
extern UNS8 motorPara[16];		/* Mapped at index 0x2002, subindex 0x01 - 0x10 */

#endif // MASTER_H
